import { mkdtemp, readdir, rename, rm } from "node:fs/promises";
import path from "node:path";

import { checkGateway } from "./check-gateway.ts";
import { checkVersions } from "./compare-schemas.ts";
import { emitContract } from "./emit-contract.ts";
import { bundleEntry, emitEntry } from "./emit-entry.ts";
import { compileValidators, writeValidators } from "./emit-validators.ts";
import {
  CLIENT_DIR,
  GENERATED_DIR,
  RUNTIME_DIR,
  VALIDATORS_DIR,
} from "./layout.ts";
import { loadConfig, sourceDigest } from "./load-config.ts";
import { loadVersions } from "./schema-store.ts";

// What every staging directory of a run for `outDir` is named after. Each run gets one of its
// own beneath this prefix, so a run that fails cleans up only what it built. A sibling of the
// generated directory, so the depth from a gateway's own modules is the one the emitted paths
// were written for.
export const stagingPrefix = (outDir: string): string => `${outDir}.staging-`;

// What a run that was interrupted rather than failed left beside the generated directory: a
// failure cleans up after itself, a signal gives it no chance to. Swept before this run builds
// its own, so abandoned directories do not accumulate.
//
// A ".previous" directory is not one of these. It is the last complete run's output, kept where
// publication could neither finish nor be undone, and the only copy of it left; the next run to
// publish replaces what it was a copy of, and removing it before that is what would lose it.
// Failing to remove one of these is not a failed generation: nothing was generated yet, and the
// name is this gateway's own, so a directory left here is only ever its own to tidy.
async function sweepAbandoned(outDir: string): Promise<void> {
  const prefix = path.basename(stagingPrefix(outDir));
  const parent = path.dirname(outDir);
  const entries = await readdir(parent).catch(() => []);
  await Promise.all(
    entries
      .filter(
        (entry) => entry.startsWith(prefix) && !entry.endsWith(".previous"),
      )
      .map((entry) =>
        rm(path.join(parent, entry), { recursive: true, force: true }).catch(
          () => undefined,
        ),
      ),
  );
}

function errorCode(error: unknown): string | undefined {
  return error instanceof Error
    ? (error as NodeJS.ErrnoException).code
    : undefined;
}

// Puts a finished run in place of the last one. The previous output is moved aside rather than
// deleted, so a publication that fails leaves it where it was.
async function publish(staging: string, outDir: string): Promise<void> {
  const previous = `${staging}.previous`;
  let moved = false;
  try {
    await rename(outDir, previous);
    moved = true;
  } catch (error: unknown) {
    // Nothing was generated for this gateway before.
    if (errorCode(error) !== "ENOENT") throw error;
  }

  try {
    await rename(staging, outDir);
  } catch (error: unknown) {
    if (moved) await rename(previous, outDir).catch(() => undefined);
    throw error;
  }

  // The swap is done, so the run has succeeded and this is tidying: what it removes is the
  // output this run replaced. A failure to remove it is not a failed generation, and reporting
  // one would say the previous output is what survived, when it has already been replaced.
  await rm(previous, { recursive: true, force: true }).catch(() => undefined);
}

// One generated directory per gateway, holding the two things a gateway produces: what it runs
// and what a caller imports. A gateway is named by its directory rather than by a configuration
// object: the entry point imports `gateway.config.ts` by path and esbuild reads that file when it
// bundles, so the configuration checked here has to be the one read from it in this run, and
// nothing else can be handed in. Checked first, and built beside the directory it replaces: a run
// that fails at any step leaves what the last complete run produced, rather than a gateway whose
// two halves came from different schemas. One run at a time per directory; nothing coordinates
// two, and a gateway is generated by one command. One run per gateway per process, too: Node
// cannot evict a module it has evaluated, so a second run reads the configuration again, and
// the schemas, which are parsed rather than imported, but is served whatever the configuration
// imports as the first run left it.
export async function generate(gatewayDir: string): Promise<void> {
  const dir = path.resolve(gatewayDir);
  // Read before a line of the gateway is evaluated. Loading it runs its modules, which takes as
  // long as they take, and a file changed while that happens would otherwise be recorded as the
  // state the run started from: the check at the end would compare the new bytes against
  // themselves and find a run to publish, having checked what the files said before.
  const sources = await sourceDigest(dir);
  const config = await loadConfig(dir);
  const versions = await loadVersions(dir);
  // loadVersions refuses a gateway with no versions, so there is a latest.
  const schemas = versions.at(-1)?.schemas ?? { operations: {} };

  // The schemas are generated from before they are read against anything else, so a schema that
  // is not a valid schema is reported as itself rather than as the disagreement it causes. Then
  // against the versions before them, and only then against the configuration: a contract that
  // breaks its callers is refused whatever the configuration makes of it.
  const compiled = compileValidators(schemas);
  checkVersions(config.id, versions);
  checkGateway(config, schemas);

  const outDir = path.join(dir, GENERATED_DIR);
  await sweepAbandoned(outDir);
  // One directory to clean up, whichever step fails: what a run leaves behind is the last
  // complete run's output, never its own.
  const staging = await mkdtemp(stagingPrefix(outDir));
  try {
    // The validators are already generated by the time anything is written: what is left is
    // putting the two halves in the staging directory, the contract last.
    const runtimeDir = path.join(staging, RUNTIME_DIR);
    await writeValidators(compiled, path.join(runtimeDir, VALIDATORS_DIR));
    await emitEntry(config.id, runtimeDir);
    await bundleEntry(runtimeDir);
    await emitContract(config.id, schemas, path.join(staging, CLIENT_DIR));

    // The bundle is built by reading the gateway's modules from disk again, the configuration
    // and whatever it imports, so a file that changed while this ran would be deployed having
    // been checked in its earlier state. The run is refused rather than published: reading them
    // again is all it takes to be sure.
    if ((await sourceDigest(dir)) !== sources) {
      throw new Error(
        `Gateway "${config.id}": ${dir} changed while it was being generated, so what was checked is not what the bundle would run. Nothing was published; run it again.`,
      );
    }
    await publish(staging, outDir);
  } catch (error: unknown) {
    await rm(staging, { recursive: true, force: true });
    throw error;
  }
}
