import { mkdtemp, rename, rm } from "node:fs/promises";
import path from "node:path";

import { checkGateway } from "./check-gateway.ts";
import { emitContract } from "./emit-contract.ts";
import { compileValidators, writeValidators } from "./emit-validators.ts";
import {
  CLIENT_DIR,
  GENERATED_DIR,
  RUNTIME_DIR,
  VALIDATORS_DIR,
} from "./layout.ts";
import { loadConfig, loadGatewaySchemas } from "./load-config.ts";

// What every staging directory of a run for `outDir` is named after. Each run gets one of its
// own beneath this prefix, so a run that fails cleans up only what it built. A sibling of the
// generated directory, so the depth from a gateway's own modules is the one the emitted paths
// were written for.
export const stagingPrefix = (outDir: string): string => `${outDir}.staging-`;

function errorCode(error: unknown): string | undefined {
  return error instanceof Error
    ? (error as NodeJS.ErrnoException).code
    : undefined;
}

// Puts a finished run in place of the last one. The previous output is moved aside rather than
// deleted, so a publication that fails leaves it where it was.
async function publish(staging: string, outDir: string): Promise<void> {
  const previous = `${staging}.previous`;
  let moved = false;
  try {
    await rename(outDir, previous);
    moved = true;
  } catch (error: unknown) {
    // Nothing was generated for this gateway before.
    if (errorCode(error) !== "ENOENT") throw error;
  }

  try {
    await rename(staging, outDir);
  } catch (error: unknown) {
    if (moved) await rename(previous, outDir).catch(() => undefined);
    throw error;
  }

  // The swap is done, so the run has succeeded and this is tidying: what it removes is the
  // output this run replaced. A failure to remove it is not a failed generation, and reporting
  // one would say the previous output is what survived, when it has already been replaced.
  await rm(previous, { recursive: true, force: true }).catch(() => undefined);
}

// One generated directory per gateway, holding the two things a gateway produces: what it runs
// and what a caller imports. A gateway is named by its directory rather than by a configuration
// object: the configuration and its schemas are read here, from the bytes on disk rather than
// from whatever a process loaded before, so what is checked is what the gateway says now.
// Checked first, and built beside the directory it replaces: a run
// that fails at any step leaves what the last complete run produced, rather than a gateway whose
// two halves came from different schemas. One run at a time per directory; nothing coordinates
// two, and a gateway is generated by one command. One run per gateway per process, too: Node
// cannot evict a module it has evaluated, so a second run reads the configuration and the fixture
// again but is served whatever they import as the first run left it.
export async function generate(gatewayDir: string): Promise<void> {
  const dir = path.resolve(gatewayDir);
  const config = await loadConfig(dir);
  const schemas = await loadGatewaySchemas(config, dir);

  // The schemas are generated from before they are read against the configuration, so a schema
  // that is not a valid schema is reported as itself rather than as the disagreement it causes.
  const compiled = compileValidators(schemas);
  checkGateway(config, schemas);

  const outDir = path.join(dir, GENERATED_DIR);
  // One directory to clean up, whichever step fails: what a run leaves behind is the last
  // complete run's output, never its own.
  const staging = await mkdtemp(stagingPrefix(outDir));
  try {
    // The validators are already generated by the time anything is written: what is left is
    // putting the two halves in the staging directory.
    await writeValidators(
      compiled,
      path.join(staging, RUNTIME_DIR, VALIDATORS_DIR),
    );
    await emitContract(config.id, schemas, path.join(staging, CLIENT_DIR));

    await publish(staging, outDir);
  } catch (error: unknown) {
    await rm(staging, { recursive: true, force: true });
    throw error;
  }
}
